/**
 * LANBeam — persistent application state.
 *
 * Wraps electron-store for paired devices, settings, and transfer history.
 * Settings here are the *source of truth* that both the renderer and the
 * Rust core read from when configuring the transfer engine.
 */
import Store from 'electron-store';
import { v4 as uuidv4 } from 'uuid';

export interface PairedDevice {
  deviceId: string;        // Stable UUID generated by the remote peer
  name: string;            // Human-readable name (e.g. "Galaxy S24")
  kind: 'phone' | 'desktop' | 'unknown';
  fingerprint: string;    // Public-key fingerprint (currently a sha256 of pairing secret)
  pairedAt: number;        // Unix ms
  lastSeen: number;        // Unix ms
}

export interface Settings {
  chunkSizeMB: number;          // 1..16, default 4
  maxParallelStreams: number;   // 1..32, default 8
  compressionMode: 'auto' | 'on' | 'off';   // default 'auto'
  warnOnSlowWifi: boolean;      // default true
  accentColor: string;          // hex, default '#00E5FF'
  quicPort: number;             // default 0 = random
  httpPort: number;             // default 0 = random
  fontChoice?: 'figtree' | 'outfit' | 'system'; // default 'figtree'
  acceptUnpairedAuto: boolean;  // FORCED false in security layer; UI can show but not set
}

export interface TransferHistoryEntry {
  id: string;
  fileName: string;
  fileSize: number;
  direction: 'in' | 'out';
  peerName: string;
  startedAt: number;
  completedAt: number;
  durationMs: number;
  averageThroughputMbps: number;
  integrityOk: boolean;
  chunkRetries: number;
}

export interface AppState {
  pairedDevices: PairedDevice[];
  settings: Settings;
  history: TransferHistoryEntry[];
  localDeviceId: string;
}

const DEFAULT_SETTINGS: Settings = {
  chunkSizeMB: 4,
  maxParallelStreams: 8,
  compressionMode: 'auto',
  warnOnSlowWifi: true,
  accentColor: '#00E5FF',
  fontChoice: 'figtree',
  quicPort: 0,
  httpPort: 0,
  acceptUnpairedAuto: false, // hard-locked
};

export class StateStore {
  private store: Store<AppState>;

  constructor() {
    this.store = new Store<AppState>({
      name: 'lanbeam-state',
      defaults: {
        pairedDevices: [],
        settings: DEFAULT_SETTINGS,
        history: [],
        localDeviceId: uuidv4(),
      },
    });
  }

  get settings(): Settings {
    return { ...this.store.get('settings') };
  }

  updateSettings(patch: Partial<Settings>): Settings {
    const next = { ...this.store.get('settings'), ...patch };
    // Security: never persist acceptUnpairedAuto=true.
    next.acceptUnpairedAuto = false;
    this.store.set('settings', next);
    return next;
  }

  get pairedDevices(): PairedDevice[] {
    return [...this.store.get('pairedDevices')];
  }

  addPairedDevice(device: PairedDevice): void {
    const devices = this.store.get('pairedDevices').filter(d => d.deviceId !== device.deviceId);
    devices.push(device);
    this.store.set('pairedDevices', devices);
  }

  removePairedDevice(deviceId: string): void {
    this.store.set('pairedDevices', this.store.get('pairedDevices').filter(d => d.deviceId !== deviceId));
  }

  touchPairedDevice(deviceId: string): void {
    const devices = this.store.get('pairedDevices').map(d =>
      d.deviceId === deviceId ? { ...d, lastSeen: Date.now() } : d
    );
    this.store.set('pairedDevices', devices);
  }

  get history(): TransferHistoryEntry[] {
    return [...this.store.get('history')];
  }

  addHistory(entry: TransferHistoryEntry): void {
    const history = [entry, ...this.store.get('history')].slice(0, 500);
    this.store.set('history', history);
  }

  get localDeviceId(): string {
    return this.store.get('localDeviceId');
  }
}
